export const POINTS = {
  // V1
  UPLOAD_CLIP: 10,
  CREATE_SPOT: 20,
  RECEIVE_LIKE: 5,
  RECEIVE_COMMENT: 3,
  RATE_SPOT: 2,
  FOLLOW_USER: 1,

  // V2
  WIN_BATTLE: 100,
  WIN_CHALLENGE: 150,
  VOTE_BATTLE: 2,
  CREATE_CREW: 50,
  LAND_TRICK: 15,
  UNLOCK_ACHIEVEMENT: 25,

  // V3
  SESSION_CHECKIN: 5,
  HOST_SESSION: 10,
  WIN_CREW_BATTLE: 200,
  WIN_EVENT_FIRST: 200,
  WIN_EVENT_SECOND: 100,
  WIN_EVENT_THIRD: 50,
  CREATE_TUTORIAL: 15,
  TUTORIAL_HELPFUL_VOTE: 1,
  FIRST_GEAR_SETUP: 5,
} as const;
