export const POINTS = {
  // V1
  UPLOAD_CLIP: 10,
  CREATE_SPOT: 20,
  RECEIVE_LIKE: 5,
  RECEIVE_COMMENT: 3,
  RATE_SPOT: 2,
  FOLLOW_USER: 1,

  // V2
  WIN_BATTLE: 100,
  WIN_CHALLENGE: 150,
  VOTE_BATTLE: 2,
  CREATE_CREW: 50,
  LAND_TRICK: 15,
  UNLOCK_ACHIEVEMENT: 25,
} as const;
